apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mynewcomponent
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mynewcomponent
    app.kubernetes.io/part-of: devfile-sample-python-basic
  name: mynewcomponent1tlj
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: mynewcomponent
    weight: null
status: {}
